# Generated by Django 3.2.7 on 2021-09-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210928_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(default='', max_length=50),
        ),
    ]
